default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: onebitfood_development

test:
  <<: *default
  database: onebitfood_test

production:
  <<: *default
  database: onebitfood_production
  username: onebitfood
  password: <%= ENV['ONEBITFOOD_DATABASE_PASSWORD'] %>
